name: Generate manifest.json

on:
  push:
    branches: [main] # or your branch
  workflow_dispatch: # lets you run it manually from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Generate manifest.json
        run: |
          node generate-manifest.js

      - name: Commit and push manifest.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add manifest.json
          git commit -m "chore: update manifest.json [auto]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true  # prevents crash if no changes
